name: "Mod Compatibility Request"
description: "Request to make Kallfix compatible with another specific mod."
title: "Mod Compatibility for <Mod Name>"
labels: ["enhancement", "compatibility"]
assignees:
  - n1luik
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for helping improve Kallfix!**

        Before submitting, please use the search function to ensure that a compatibility request for this mod has not already been made.

  - type: input
    id: mod-name
    attributes:
      label: "Mod Name"
      description: "What is the name of the mod you want Kallfix to be compatible with?"
      placeholder: "e.g., Sodium"
    validations:
      required: true

  - type: input
    id: mod-link
    attributes:
      label: "Mod Link"
      description: "Please provide a link to the mod's official page or download source (e.g., CurseForge, Modrinth, GitHub)."
      placeholder: "https://www.curseforge.com/minecraft/mc-mods/sodium"
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: "Mod Version"
      description: "What is the exact version of the mod you are using?"
      placeholder: "e.g., 0.5.8"
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: "Minecraft Version"
      description: "Which version of Minecraft are you using?"
      placeholder: "e.g., 1.20.1"
    validations:
      required: true

  - type: input
    id: mod-loader
    attributes:
      label: "Mod Loader"
      description: "Which mod loader does this modpack use?"
      placeholder: "e.g., Forge"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason for Compatibility Request"
      description: |
        Please describe the issue in detail. 
        - What happens when you use both mods together?
        - Are there crashes, visual glitches, performance drops, or specific features that don't work?
        - What do you expect to happen?
        - If there is a crash, please be prepared to provide a crash report in a follow-up comment.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm the following before submitting your request."
      options:
        - label: "I have searched the existing issues and confirmed this is not a duplicate."
          required: true
        - label: "I have provided accurate and direct links to the mod in question."
          required: true
        - label: "I understand that compatibility is not guaranteed and is at the discretion of the project owner."
          required: true
