name: Build

on: 
 workflow_dispatch:
 push: 
   branches:
      - Code
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         ref: Code

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.1.1'

      - name: Delete first non-comment line of gradle.properties
        shell: pwsh
        run: |
          $filePath = "gradle.properties"
          $lines = Get-Content $filePath
          $targetIndex = -1
          # Find the index of the first non-comment, non-empty line
          for ($i = 0; $i -lt $lines.Length; $i++) {
          $line = $lines[$i].Trim() # Trim whitespace from the beginning and end
          if ($line -ne "" -and $line -notlike "#*") {
          $targetIndex = $i
          break # Found the line, exit the loop
          }
          }
          # If a non-comment line was found, remove it
          if ($targetIndex -ne -1) {
          Write-Host "Found first non-comment line at index $targetIndex: $($lines[$targetIndex])"
          # Use Select-Object -ExcludeIndex to remove the line by index
          $newContent = $lines | Select-Object -ExcludeIndex $targetIndex
          Set-Content $filePath -Value $newContent -Force
          Write-Host "Successfully removed the line."
          } else {
          Write-Host "No non-comment line found to remove in $($filePath)."
          }

      - name: Build with Gradle
        run: gradle jar

      - name: Create timestamp
        id: create_timestamp
        run: echo "timestamp=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: 1.20.1-6.0.0-Forge_NeoForge-${{ steps.create_timestamp.outputs.timestamp }}
          github-draft: false
          github-prerelease: true
          files: install/build/libs/*.jar

      - uses: actions/upload-artifact@v4
        with:
          name: Build Artifact
          include-hidden-files: true
          path: |
            **/logs/
            **/crash-reports/
            build/libs
            gradle.properties
          retention-days: 1
        if: always()
